### ISSUE TITLE
Matrix field cannot be cloned because of jQuery error

### ISSUE THREAD

**Issue by yingban** [engram-design/FieldManager#70] opened 2020-07-28 07:40 UTC
Hi,

I am trying to clone a matrix field, and it seems not working since the last update.
I got the following error in the console:

<img width="1919" alt="Screenshot 2020-07-28 at 09 35 57" src="https://user-images.githubusercontent.com/3421450/88634135-4a749100-d0b6-11ea-8fa5-baa609a8e07f.png">

Thank you in advance for your help !

### Additional info

- Plugin version: 2.1.8
- Craft version:  3.4.29.1

**Comment by engram-design** [comment] 2020-07-28 09:03
I can't seem to replicate this. Can you clear all the caches in Utilities? Are you able to clone any other field?

**Comment by yingban** [comment] 2020-07-28 13:16
Thanks for your reply.
I cleared cache and the issue is still there.

I have tried with a Redactor type, it works well.
Also tested with another Matrix field, it works as well .... so it might come from plugins with special fields like "link" or "super table"

**Comment by engram-design** [comment] 2020-07-29 02:31
Interesting, can you share the fields in your Matrix field that you're unable to clone? Hopefully, I can reproduce.

**Comment by yingban** [comment] 2020-07-29 07:57
Really strange, I have tried with another Matrix field which contains only 1 block, it's working.

With the one attached, I have tried to remove one by one block (until 0 block), then clone, and it was still not working.

(it was on Firefox, but just tried with Chrome, same result)

[export.json.zip](https://github.com/verbb/field-manager/files/4993455/export.json.zip)

**Comment by CreateSean** [comment] 2020-08-31 15:31
I'm having this same issue. In the console I get this error:

```
jquery.js:10099 POST https://hotd-craft.ddev.site/index.php?p=access/actions/field-manager/base/clone-field 500
send @ jquery.js:10099
ajax @ jquery.js:9682
postActionRequest @ Craft.js:508
saveSettings @ field-manager.js:281
(anonymous) @ garnish.js:893
o @ jquery.js:10771
dispatch @ jquery.js:5429
v.handle @ jquery.js:5233
trigger @ jquery.js:8715
(anonymous) @ jquery.js:8793
each @ jquery.js:381
each @ jquery.js:203
trigger @ jquery.js:8792
click.garnish-activate @ garnish.js:960
dispatch @ jquery.js:5429
v.handle @ jquery.js:5233
field-manager.js:284 Uncaught TypeError: Cannot read property 'error' of null
    at s.constructor.<anonymous> (field-manager.js:284)
    at o (jquery.js:10771)
    at Object.error (Craft.js:529)
    at u (jquery.js:3496)
    at Object.fireWith [as rejectWith] (jquery.js:3626)
    at S (jquery.js:9788)
    at XMLHttpRequest.<anonymous> (jquery.js:10047)
```

Not sure if this is due to the fact that I'm setting widths for some of my new fields as per Craft 3.5 updates.

I then tried exporting to json and importoing with a new name and got this error page.

```
Page not found.
↵
Caused by: Invalid Route – yii\base\InvalidRouteException
Unable to resolve the request "".
in /var/www/html/vendor/yiisoft/yii2/base/Module.php at line 537
```

Have attached my export file
[export.zip](https://github.com/verbb/field-manager/files/5151187/export.zip)

**Comment by engram-design** [comment] 2020-09-05 07:05
@CreateSean Should be fixed in [2.2.0](https://github.com/verbb/field-manager/releases/tag/2.2.0)

**Closed as completed by engram-design** 2020-09-05 07:05 UTC

**Comment by jpcarpenter** [comment] 2021-12-13 21:19
I'm getting the exact same error as @CreateSean. Attempting to clone a matrix field with super tables within.

Field Manager 2.2.4
Craft CMS 3.7.25.1

**Comment by engram-design** [comment] 2021-12-19 22:26
@jpcarpenter Are you able to look at the Network tab (in web developer tools), find the request that errored, and look at the Preview tab? It should provide more info about the error, as I can't replicate. Also ensure `devMode` is on.

I'd also look in your `web.log` files for an error related to field-manager?

**Comment by jpcarpenter** [comment] 2021-12-20 17:52
@engram-design I'm not able to reproduce the issue again. I ended up updating Craft from 3.7.25.1 => 3.7.26 and it resolved itself.
